### PR TITLE
Update config: Remove 'position', add 'side' and 'align' properties

### PR DESCRIPTION
**Pull request by wsxiaolin**
Hello,

I've noticed that the current configuration file includes an unused and unsupported `position` property. Considering the existing schema supports 'side' and 'align' configurations, I decided to remove the `position` property and introduce these two valid properties instead.

Screenshot_20240331_125208

The changes include:

1. Removal of the 'position' configuration entry.
2. Addition of 'side' and 'align' configurations to align with the expected schema and improve the flexibility and functionality of our system.

I have tested these changes at https://discourse.theme-creator.io/user_themes/8415/preview and everything seems to be working as expected. Please review this pull request and let me know if you have any feedback or suggestions.

Thanks

### CODE REVIEW

**Comment by wsxiaolin** [comment]
提交错地方了（汗

**Comment by CIVITAS-John** [comment]
Great, thanks!

**Comment by CIVITAS-John** [comment]
没错呀问题是？

**Comment by wsxiaolin** [comment]
> 没错呀问题是？

不应该提交到https://github.com/NetLogo-Mobile/Forum-Tutorial-Component/pull/1/commits 嘛？那个仓库领先这个好几个commit，我提交到那里去了

**Pull request closed without merging**
